## Data Processing

In [1]:
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [2]:
# ndmin mean size of array 
a = np.array([1,2,3,4,5], ndmin=3)
print(a)

[[[1 2 3 4 5]]]


In [3]:
a = np.array([1,2,3], dtype=complex)
b = np.array([1,2,3], dtype=float)

print(a)
print(b)


[1.+0.j 2.+0.j 3.+0.j]
[1. 2. 3.]


In [4]:
import pandas as pd
data = np.array(['a','b','c','d','e'])
s = pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
4    e
dtype: object


In [5]:
data = {'Name':['Tom','Jerry','Jack','Oggy'],'Age':[24,34,54,12]}
df = pd.DataFrame(data,index=['rank1','rank2','rank3','rank4'])
print(df)

        Name  Age
rank1    Tom   24
rank2  Jerry   34
rank3   Jack   54
rank4   Oggy   12


In [6]:
# Panel Module Remove From new Version of Pandas

# data = { 'Item1': pd.DataFrame(np.random.randn(4,3)),
#          'Item2': pd.DataFrame(np.random.randn(4,2))
# }
# p = pd.Panel(data)
# print(p)

## Data Cleansing

In [7]:
import pandas as pd
import numpy as np

print(np.random.randn(5,3))
df = pd.DataFrame(np.random.randn(5,3), index=['a','c','e','f','h'], columns=['one', 'two', 'three'])

df = df.reindex(['a','b','c','d','e','f','g','h'])

print(df)

[[-0.02864166  0.61791067  1.03672812]
 [-0.94199299 -0.27225905  0.56912782]
 [ 0.55604507 -0.66393712  0.56421183]
 [ 0.12903391  0.26700379 -0.7387224 ]
 [ 0.33061451 -0.44676972 -0.10688624]]
        one       two     three
a -0.158994  0.525862  0.084301
b       NaN       NaN       NaN
c  1.002819 -1.503696  0.806397
d       NaN       NaN       NaN
e -0.042532 -0.712726  0.504240
f  0.117453 -1.023742 -1.303904
g       NaN       NaN       NaN
h -1.053899 -0.603865  0.514631


In [8]:
df.isnull()

one    two  three
a  False  False  False
b   True   True   True
c  False  False  False
d   True   True   True
e  False  False  False
f  False  False  False
g   True   True   True
h  False  False  False

##### fillna function fill the NAN value to respected add as parameter in Function

In [9]:
# df.fillna(0)

##### fillna function we can add method='pad' or method='fill' it's mean add forward value

In [10]:
# print(df.fillna(method='pad'))

##### fillna function we can add method='bfill' or method='backfill' it's mean add backward value

In [11]:
print(df.fillna(method='bfill'))

        one       two     three
a -0.158994  0.525862  0.084301
b  1.002819 -1.503696  0.806397
c  1.002819 -1.503696  0.806397
d -0.042532 -0.712726  0.504240
e -0.042532 -0.712726  0.504240
f  0.117453 -1.023742 -1.303904
g -1.053899 -0.603865  0.514631
h -1.053899 -0.603865  0.514631


##### dropna functin use delete all null value

In [12]:
df.dropna()

one       two     three
a -0.158994  0.525862  0.084301
c  1.002819 -1.503696  0.806397
e -0.042532 -0.712726  0.504240
f  0.117453 -1.023742 -1.303904
h -1.053899 -0.603865  0.514631

##### replace function use for repalce value 

In [13]:
df  = pd.DataFrame({
    'One':[10,20,30,40,50,2000],
    'Two':[1000,0,10,23,45,78]
})
df.replace({2000:1234, 1000:9870})

One   Two
0    10  9870
1    20     0
2    30    10
3    40    23
4    50    45
5  1234    78

## Processing CSV Data

In [14]:
import pandas as pd

data = pd.read_csv('top_youtube_channel_data.csv')
data

rank                     youtuber  subscribers      video views  \
0      1                    T-Series     213000000  188,073,919,029   
1      2              YouTube Movies     150000000  167,122,746,349   
2      3  Cocomelon - Nursery Rhymes     133000000  126,822,520,940   
3      4                   SET India     131000000  101,541,977,714   
4      5                       Music     116000000   78,437,871,689   
..   ...                          ...          ...              ...   
95    96                  Markiplier      32600000   18,011,837,263   
96    97             Like Nastya ESP      32600000   15,144,858,210   
97    98                Ryan's World      32400000   51,312,603,726   
98    99                    ABP News      32300000    9,850,740,503   
99   100          Desi Music Factory      32200000    9,115,577,588   

    video count           category  started   
0       16708.0             Music       2006  
1           NaN  Film & Animation       2015  
2         751.0         Education       2006  
3       78334.0             Shows       2006  
4           NaN             Music       2013  
..          ...                ...       ...  
95       5129.0            Gaming       2012  
96        584.0     Entertainment       2017  
97       2155.0     Entertainment       2015  
98     209351.0    People & Blogs       2012  
99        122.0             Music       2014  

[100 rows x 7 columns]

In [15]:
data.head()

rank                     youtuber  subscribers      video views  \
0     1                    T-Series     213000000  188,073,919,029   
1     2              YouTube Movies     150000000  167,122,746,349   
2     3  Cocomelon - Nursery Rhymes     133000000  126,822,520,940   
3     4                   SET India     131000000  101,541,977,714   
4     5                       Music     116000000   78,437,871,689   

   video count           category  started   
0      16708.0             Music       2006  
1          NaN  Film & Animation       2015  
2        751.0         Education       2006  
3      78334.0             Shows       2006  
4          NaN             Music       2013

In [16]:
data.tail()

rank             youtuber  subscribers     video views  video count  \
95    96          Markiplier      32600000  18,011,837,263       5129.0   
96    97     Like Nastya ESP      32600000  15,144,858,210        584.0   
97    98        Ryan's World      32400000  51,312,603,726       2155.0   
98    99            ABP News      32300000   9,850,740,503     209351.0   
99   100  Desi Music Factory      32200000   9,115,577,588        122.0   

           category  started   
95          Gaming       2012  
96   Entertainment       2017  
97   Entertainment       2015  
98  People & Blogs       2012  
99           Music       2014

In [17]:
data.head()['category']

0               Music 
1    Film & Animation 
2           Education 
3               Shows 
4               Music 
Name: category, dtype: object

In [18]:
print(data.loc[:,['rank','category']].head())

   rank           category
0     1             Music 
1     2  Film & Animation 
2     3         Education 
3     4             Shows 
4     5             Music 


In [19]:
data.loc[1:10,['rank','category']]

rank           category
1      2  Film & Animation 
2      3         Education 
3      4             Shows 
4      5             Music 
5      6            Gaming 
6      7     Entertainment 
7      8    People & Blogs 
8      9            Gaming 
9     10    People & Blogs 
10    11            Sports

 ### Processing JSON Data

In [20]:
import pandas as pd

data = pd.read_json('processing_json_data.json')
data

ID      Name  Salary   StartDate        Dept
0   1      Rick  623.30    1/1/2012          IT
1   2       Dan  515.20   9/23/2013  Operations
2   3  Michelle  611.00  11/15/2014          IT
3   4      Ryan  729.00   5/11/2014          HR
4   5      Gary  843.25   3/27/2015     Finance
5   6      Nina  578.00   5/21/2013          IT
6   7     Simon  632.80   7/30/2013  Operations
7   8      Guru  722.50   6/17/2014     Finance

In [21]:
data.loc[:, ['Salary', 'Dept']]

Salary        Dept
0  623.30          IT
1  515.20  Operations
2  611.00          IT
3  729.00          HR
4  843.25     Finance
5  578.00          IT
6  632.80  Operations
7  722.50     Finance

In [22]:
data.loc[[1,3,4],['Salary','Dept']]

Salary        Dept
1  515.20  Operations
3  729.00          HR
4  843.25     Finance

In [23]:
data.to_json(orient="records")

'[{"ID":1,"Name":"Rick","Salary":623.3,"StartDate":"1\\/1\\/2012","Dept":"IT"},{"ID":2,"Name":"Dan","Salary":515.2,"StartDate":"9\\/23\\/2013","Dept":"Operations"},{"ID":3,"Name":"Michelle","Salary":611.0,"StartDate":"11\\/15\\/2014","Dept":"IT"},{"ID":4,"Name":"Ryan","Salary":729.0,"StartDate":"5\\/11\\/2014","Dept":"HR"},{"ID":5,"Name":"Gary","Salary":843.25,"StartDate":"3\\/27\\/2015","Dept":"Finance"},{"ID":6,"Name":"Nina","Salary":578.0,"StartDate":"5\\/21\\/2013","Dept":"IT"},{"ID":7,"Name":"Simon","Salary":632.8,"StartDate":"7\\/30\\/2013","Dept":"Operations"},{"ID":8,"Name":"Guru","Salary":722.5,"StartDate":"6\\/17\\/2014","Dept":"Finance"}]'

In [24]:
data.to_json(orient='records', lines=True)

'{"ID":1,"Name":"Rick","Salary":623.3,"StartDate":"1\\/1\\/2012","Dept":"IT"}\n{"ID":2,"Name":"Dan","Salary":515.2,"StartDate":"9\\/23\\/2013","Dept":"Operations"}\n{"ID":3,"Name":"Michelle","Salary":611.0,"StartDate":"11\\/15\\/2014","Dept":"IT"}\n{"ID":4,"Name":"Ryan","Salary":729.0,"StartDate":"5\\/11\\/2014","Dept":"HR"}\n{"ID":5,"Name":"Gary","Salary":843.25,"StartDate":"3\\/27\\/2015","Dept":"Finance"}\n{"ID":6,"Name":"Nina","Salary":578.0,"StartDate":"5\\/21\\/2013","Dept":"IT"}\n{"ID":7,"Name":"Simon","Salary":632.8,"StartDate":"7\\/30\\/2013","Dept":"Operations"}\n{"ID":8,"Name":"Guru","Salary":722.5,"StartDate":"6\\/17\\/2014","Dept":"Finance"}\n'

## Processing XLS Data

> ##### *convert csv to excel*

In [25]:
import pandas as pd

data = pd.read_csv("top_youtube_channel_data.csv")
data.to_excel("top_youtube_channel_data.xlsx", index=None, header=True)

> #### *Reading Excel File*

In [26]:
data = pd.read_excel("top_youtube_channel_data.xlsx")
data

rank                     youtuber  subscribers      video views  \
0      1                    T-Series     213000000  188,073,919,029   
1      2              YouTube Movies     150000000  167,122,746,349   
2      3  Cocomelon - Nursery Rhymes     133000000  126,822,520,940   
3      4                   SET India     131000000  101,541,977,714   
4      5                       Music     116000000   78,437,871,689   
..   ...                          ...          ...              ...   
95    96                  Markiplier      32600000   18,011,837,263   
96    97             Like Nastya ESP      32600000   15,144,858,210   
97    98                Ryan's World      32400000   51,312,603,726   
98    99                    ABP News      32300000    9,850,740,503   
99   100          Desi Music Factory      32200000    9,115,577,588   

    video count           category  started   
0       16708.0             Music       2006  
1           NaN  Film & Animation       2015  
2         751.0         Education       2006  
3       78334.0             Shows       2006  
4           NaN             Music       2013  
..          ...                ...       ...  
95       5129.0            Gaming       2012  
96        584.0     Entertainment       2017  
97       2155.0     Entertainment       2015  
98     209351.0    People & Blogs       2012  
99        122.0             Music       2014  

[100 rows x 7 columns]

In [27]:
data.loc[[1,2,3,5,6,7], ['youtuber','category']]

youtuber           category
1              YouTube Movies   Film & Animation 
2  Cocomelon - Nursery Rhymes          Education 
3                   SET India              Shows 
5                   PewDiePie             Gaming 
6                     MrBeast      Entertainment 
7             Kids Diana Show     People & Blogs

In [28]:
import pandas as pd 
with pd.ExcelFile('top_youtube_channel_data.xlsx') as xls:
    df1 = pd.read_excel(xls, 'Sheet1')
    # df2 = pd.read_excel(xls, 'Sheet2')

df1
# try:
#     df2
# except:
#     print("Not a Sheet2")

rank                     youtuber  subscribers      video views  \
0      1                    T-Series     213000000  188,073,919,029   
1      2              YouTube Movies     150000000  167,122,746,349   
2      3  Cocomelon - Nursery Rhymes     133000000  126,822,520,940   
3      4                   SET India     131000000  101,541,977,714   
4      5                       Music     116000000   78,437,871,689   
..   ...                          ...          ...              ...   
95    96                  Markiplier      32600000   18,011,837,263   
96    97             Like Nastya ESP      32600000   15,144,858,210   
97    98                Ryan's World      32400000   51,312,603,726   
98    99                    ABP News      32300000    9,850,740,503   
99   100          Desi Music Factory      32200000    9,115,577,588   

    video count           category  started   
0       16708.0             Music       2006  
1           NaN  Film & Animation       2015  
2         751.0         Education       2006  
3       78334.0             Shows       2006  
4           NaN             Music       2013  
..          ...                ...       ...  
95       5129.0            Gaming       2012  
96        584.0     Entertainment       2017  
97       2155.0     Entertainment       2015  
98     209351.0    People & Blogs       2012  
99        122.0             Music       2014  

[100 rows x 7 columns]

> ##### *Relational Database*

In [29]:
!pip install sqlalchemy

In [30]:
from sqlalchemy import create_engine
import pandas as pd

data = pd.read_csv("top_youtube_channel_data.csv")

# Create the db engine
engine = create_engine('sqlite:///:memory:')

# Store the DataFrame as table 
data.to_sql('data_table',engine)

# Query 1 on the relational table
res1 = pd.read_sql_query('SELECT * FROM data_table', engine)
print("Result 1")
print(res1)
print(" ")

# Query 2 on the realtional Database
res2 = pd.read_sql_query('SELECT category,youtuber,rank FROM data_table', engine)
print("Result 2")
print(res2)

Result 1
    index  rank                     youtuber  subscribers      video views  \
0       0     1                    T-Series     213000000  188,073,919,029   
1       1     2              YouTube Movies     150000000  167,122,746,349   
2       2     3  Cocomelon - Nursery Rhymes     133000000  126,822,520,940   
3       3     4                   SET India     131000000  101,541,977,714   
4       4     5                       Music     116000000   78,437,871,689   
..    ...   ...                          ...          ...              ...   
95     95    96                  Markiplier      32600000   18,011,837,263   
96     96    97             Like Nastya ESP      32600000   15,144,858,210   
97     97    98                Ryan's World      32400000   51,312,603,726   
98     98    99                    ABP News      32300000    9,850,740,503   
99     99   100          Desi Music Factory      32200000    9,115,577,588   

    video count           category  started   
0      

> ##### *NoSQL Database*

In [31]:
!pip install pymongo

In [32]:
from pymongo import MongoClient
from pprint import pprint

# Choose the appropriate client
client = MongoClient()

# Connect to the test db
db = client.test

# Use the Employee Collection
employee = db.employee
employee_details = {
    'Name': 'Dev Darji',
    'Address': 'Shivdhara Residency',
    'Age': '23'
}

# employee.insert_one(employee_details)
# employee.find_one({'Age': '23'})

# Use the insert method
# result = employee.insert_one(employee_details)
# result

# Query for the inserted document.
# queryResult = employee.find_one({'Age':'23'})
# pprint(queryResult)

> ### *Date and Time* 

- *Date Time Representation*
- *Date Time Arithmetic*
- *Date Time Comparison*

>> ##### *Date time Representation* 

In [33]:
import datetime

print("Print the date of Today:", datetime.datetime.today())

Print the date of Today: 2022-06-01 18:16:33.489964


In [34]:
date_today = datetime.date.today()
print("Today Date : ",date_today)

Today Date :  2022-06-01


In [35]:
print("This Year : ", date_today.year)

This Year :  2022


In [36]:
print("This Month : ", date_today.month)

This Month :  6


In [37]:
print("This week day",date_today.day)

This week day 1


In [38]:
print("Month Name : ", date_today.strftime('%B'))

Month Name :  June


In [39]:
print("Week Day Name : ", date_today.strftime('%A'))

Week Day Name :  Wednesday


>> ##### *Date Time Arithmetic*

In [40]:
import datetime

# Capture the First Date
day1 = datetime.date(2022, 5, 31)
print("day1 : ", day1.ctime())

day1 :  Tue May 31 00:00:00 2022


In [41]:
day2 = datetime.date(2022, 6, 25)
print("day2 : ", day2.ctime())

day2 :  Sat Jun 25 00:00:00 2022


In [42]:
print("Number of Days : ", day2-day1)

Number of Days :  25 days, 0:00:00


In [43]:
date_today = datetime.date.today()
print(date_today)

2022-06-01


In [44]:
# Create a delta of 4 days
no_of_days = datetime.timedelta(days=4)
print("No of Days", no_of_days)

No of Days 4 days, 0:00:00


In [45]:
before_four_days = date_today -no_of_days
print("Before 4 Days", before_four_days)

Before 4 Days 2022-05-28


In [46]:
after_four_days = date_today + no_of_days
print("After 4 Days", after_four_days)

After 4 Days 2022-06-05


>> ##### *Date Time Comparison*

In [47]:
import datetime

date_today = datetime.date.today()

no_of_days = datetime.timedelta(days=4)

before_four_days = date_today - no_of_days
print("Before Four Days : ", before_four_days)

after_four_days = date_today + no_of_days
print("After Four Days : ", after_four_days)

date1 = datetime.date(2022,5,28)
print("Date1 : ",date1)

if date1 == before_four_days:
    print("Same Date")
if date_today > date1:
    print("Past Date")
if date1 < after_four_days:
    print("Future Days")

Before Four Days :  2022-05-28
After Four Days :  2022-06-05
Date1 :  2022-05-28
Same Date
Past Date
Future Days


> ### Data Wrangling

>> ##### Merging Data

In [48]:
import pandas as pd

left = pd.DataFrame({
    'id':[1,2,3,4,5],
    'Name':['Dev','Ravi','Kiran','Haresh','Mayur'],
    'subject_id':['sub1','sub2','sub3','sub4','sub5']
})

right = pd.DataFrame({
    'id':[1,2,3,4,5],
    'Name':['Darshan','Suhag','Karan','Parth','Raju'],
    'subject_id':['sub1','sub2','sub3','sub4','sub5']
})

print(left)
print(right)

   id    Name subject_id
0   1     Dev       sub1
1   2    Ravi       sub2
2   3   Kiran       sub3
3   4  Haresh       sub4
4   5   Mayur       sub5
   id     Name subject_id
0   1  Darshan       sub1
1   2    Suhag       sub2
2   3    Karan       sub3
3   4    Parth       sub4
4   5     Raju       sub5


>> ##### *Grouping Data*

In [49]:
# import the pandas library
import pandas as pd

ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
    'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
    'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
    'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
    'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)

grouped = df.groupby('Year')
print(grouped.get_group(2015))

      Team  Rank  Year  Points
1   Riders     2  2015     789
3   Devils     3  2015     673
5    kings     4  2015     812
10  Royals     1  2015     804


>> #### *Concatenating Data*

In [50]:
print(pd.concat([left, right]))

   id     Name subject_id
0   1      Dev       sub1
1   2     Ravi       sub2
2   3    Kiran       sub3
3   4   Haresh       sub4
4   5    Mayur       sub5
0   1  Darshan       sub1
1   2    Suhag       sub2
2   3    Karan       sub3
3   4    Parth       sub4
4   5     Raju       sub5


> ### Data Aggregation

In [51]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(10,4),
                  index=pd.date_range('1/1/2000', periods=10),
                  columns=['A','B','C','D'])
df

A         B         C         D
2000-01-01  1.166628 -0.377621 -0.425730  1.647737
2000-01-02 -1.177093 -1.794438 -1.127914 -1.370293
2000-01-03  1.190205 -0.055747  0.313279 -0.505850
2000-01-04 -1.356973  0.888152 -0.617353  0.434275
2000-01-05  0.416298 -1.297181 -1.416315 -0.611810
2000-01-06  0.271700 -0.112329  0.308586  0.774573
2000-01-07  1.350370 -0.644341 -1.632185  0.529025
2000-01-08 -0.936359  1.029574 -0.405724  1.376959
2000-01-09 -0.350212  0.186073  0.481101 -0.292802
2000-01-10  0.895470  1.117392  1.276203  1.410038

In [52]:
r = df.rolling(window=3, min_periods=1)
print(r)

Rolling [window=3,min_periods=1,center=False,axis=0,method=single]


In [53]:
print(df)
print(r.aggregate(np.sum))

                   A         B         C         D
2000-01-01  1.166628 -0.377621 -0.425730  1.647737
2000-01-02 -1.177093 -1.794438 -1.127914 -1.370293
2000-01-03  1.190205 -0.055747  0.313279 -0.505850
2000-01-04 -1.356973  0.888152 -0.617353  0.434275
2000-01-05  0.416298 -1.297181 -1.416315 -0.611810
2000-01-06  0.271700 -0.112329  0.308586  0.774573
2000-01-07  1.350370 -0.644341 -1.632185  0.529025
2000-01-08 -0.936359  1.029574 -0.405724  1.376959
2000-01-09 -0.350212  0.186073  0.481101 -0.292802
2000-01-10  0.895470  1.117392  1.276203  1.410038
                   A         B         C         D
2000-01-01  1.166628 -0.377621 -0.425730  1.647737
2000-01-02 -0.010465 -2.172060 -1.553644  0.277444
2000-01-03  1.179740 -2.227807 -1.240365 -0.228406
2000-01-04 -1.343861 -0.962033 -1.431988 -1.441869
2000-01-05  0.249530 -0.464775 -1.720389 -0.683386
2000-01-06 -0.668975 -0.521358 -1.725082  0.597037
2000-01-07  2.038368 -2.053851 -2.739913  0.691788
2000-01-08  0.685711  0.272903 

In [54]:
print(df)
print(r['A'].aggregate(np.sum))

                   A         B         C         D
2000-01-01  1.166628 -0.377621 -0.425730  1.647737
2000-01-02 -1.177093 -1.794438 -1.127914 -1.370293
2000-01-03  1.190205 -0.055747  0.313279 -0.505850
2000-01-04 -1.356973  0.888152 -0.617353  0.434275
2000-01-05  0.416298 -1.297181 -1.416315 -0.611810
2000-01-06  0.271700 -0.112329  0.308586  0.774573
2000-01-07  1.350370 -0.644341 -1.632185  0.529025
2000-01-08 -0.936359  1.029574 -0.405724  1.376959
2000-01-09 -0.350212  0.186073  0.481101 -0.292802
2000-01-10  0.895470  1.117392  1.276203  1.410038
2000-01-01    1.166628
2000-01-02   -0.010465
2000-01-03    1.179740
2000-01-04   -1.343861
2000-01-05    0.249530
2000-01-06   -0.668975
2000-01-07    2.038368
2000-01-08    0.685711
2000-01-09    0.063798
2000-01-10   -0.391101
Freq: D, Name: A, dtype: float64


In [55]:
print(df)
print(r[['A','B']].aggregate(np.sum))

                   A         B         C         D
2000-01-01  1.166628 -0.377621 -0.425730  1.647737
2000-01-02 -1.177093 -1.794438 -1.127914 -1.370293
2000-01-03  1.190205 -0.055747  0.313279 -0.505850
2000-01-04 -1.356973  0.888152 -0.617353  0.434275
2000-01-05  0.416298 -1.297181 -1.416315 -0.611810
2000-01-06  0.271700 -0.112329  0.308586  0.774573
2000-01-07  1.350370 -0.644341 -1.632185  0.529025
2000-01-08 -0.936359  1.029574 -0.405724  1.376959
2000-01-09 -0.350212  0.186073  0.481101 -0.292802
2000-01-10  0.895470  1.117392  1.276203  1.410038
                   A         B
2000-01-01  1.166628 -0.377621
2000-01-02 -0.010465 -2.172060
2000-01-03  1.179740 -2.227807
2000-01-04 -1.343861 -0.962033
2000-01-05  0.249530 -0.464775
2000-01-06 -0.668975 -0.521358
2000-01-07  2.038368 -2.053851
2000-01-08  0.685711  0.272903
2000-01-09  0.063798  0.571306
2000-01-10 -0.391101  2.333039
